FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["FloralImage.API/FloralImage.API.csproj", "FloralImage.API/"]
COPY ["FloralImage.DTO/FloralImage.DTO.csproj", "FloralImage.DTO/"]
COPY ["FloralImage.Domain/FloralImage.Domain.csproj", "FloralImage.Domain/"]
COPY ["FloralImage.Persistence/FloralImage.Persistence.csproj", "FloralImage.Persistence/"]
COPY ["FloralImage.Service/FloralImage.Service.csproj", "FloralImage.Service/"]
COPY ["FloralImage.DataAccess/FloralImage.DataAccess.csproj", "FloralImage.DataAccess/"]
COPY ["FloralImage.Infrastructure/FloralImage.Infrastructure.csproj", "FloralImage.Infrastructure/"]
COPY ["FloralImage.Utils/FloralImage.Utils.csproj", "FloralImage.Utils/"]
RUN dotnet restore "FloralImage.API/FloralImage.API.csproj"
COPY . .
WORKDIR "/src/FloralImage.API"
RUN dotnet build "FloralImage.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "FloralImage.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FloralImage.API.dll"]