FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Snarf.API/Snarf.API.csproj", "Snarf.API/"]
COPY ["Snarf.DTO/Snarf.DTO.csproj", "Snarf.DTO/"]
COPY ["Snarf.Domain/Snarf.Domain.csproj", "Snarf.Domain/"]
COPY ["Snarf.Persistence/Snarf.Persistence.csproj", "Snarf.Persistence/"]
COPY ["Snarf.Service/Snarf.Service.csproj", "Snarf.Service/"]
COPY ["Snarf.DataAccess/Snarf.DataAccess.csproj", "Snarf.DataAccess/"]
COPY ["Snarf.Infrastructure/Snarf.Infrastructure.csproj", "Snarf.Infrastructure/"]
COPY ["Snarf.Utils/Snarf.Utils.csproj", "Snarf.Utils/"]
RUN dotnet restore "Snarf.API/Snarf.API.csproj"
COPY . .
WORKDIR "/src/Snarf.API"
RUN dotnet build "Snarf.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Snarf.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Snarf.API.dll"]