namespace Snarf.Domain.Enum.UserDetails
{
    public enum ExpressionStyle
    {
        Bear,
        Biker,
        Bro,
        CleanCut,
        Corporate,
        Daddy,
        Discreet,
        Femme,
        Gaymer,
        Nerd,
        Goth,
        BoyNextDoor,
        Jock,
        Leather,
        Nudist,
        Otter,
        Poz,
        Punk,
        Pup,
        Rugged,
        Skater,
        Son,
        Sporty,
        Surfer,
        Swinger,
        Trans,
        Trendy,
        Trucker,
        Twink,
        InclusivePlus
    }
}