enum ExpressionStyle {
  bear,
  biker,
  bro,
  cleanCut,
  corporate,
  daddy,
  discreet,
  femme,
  gaymer,
  nerd,
  goth,
  boyNextDoor,
  jock,
  leather,
  nudist,
  otter,
  poz,
  punk,
  pup,
  rugged,
  skater,
  son,
  sporty,
  surfer,
  swinger,
  trans,
  trendy,
  trucker,
  twink,
  inclusivePlus,
}

extension ExpressionStyleLabel on ExpressionStyle {
  static const _pt = {
    ExpressionStyle.bear: 'Urso',
    ExpressionStyle.biker: 'Motociclista',
    ExpressionStyle.bro: 'Bro',
    ExpressionStyle.cleanCut: 'Estilo Limpo',
    ExpressionStyle.corporate: 'Corporativo',
    ExpressionStyle.daddy: 'Papai',
    ExpressionStyle.discreet: 'Discreto',
    ExpressionStyle.femme: 'Femme',
    ExpressionStyle.gaymer: 'Gaymer',
    ExpressionStyle.nerd: 'Nerd',
    ExpressionStyle.goth: 'Gótico',
    ExpressionStyle.boyNextDoor: 'Rapaz da Porta ao Lado',
    ExpressionStyle.jock: 'Atleta',
    ExpressionStyle.leather: 'Couro',
    ExpressionStyle.nudist: 'Nudista',
    ExpressionStyle.otter: 'Lontra',
    ExpressionStyle.poz: 'Positivo',
    ExpressionStyle.punk: 'Punk',
    ExpressionStyle.pup: 'Cachorro',
    ExpressionStyle.rugged: 'Rústico',
    ExpressionStyle.skater: 'Skatista',
    ExpressionStyle.son: 'Filho',
    ExpressionStyle.sporty: 'Esportivo',
    ExpressionStyle.surfer: 'Surfista',
    ExpressionStyle.swinger: 'Troca de Casais',
    ExpressionStyle.trans: 'Trans',
    ExpressionStyle.trendy: 'Na moda',
    ExpressionStyle.trucker: 'Caminhoneiro',
    ExpressionStyle.twink: 'Twink',
    ExpressionStyle.inclusivePlus: 'I+',
  };

  String get label => _pt[this]!;
}