enum Fetish {
  bodyArmpits,
  bodyAss,
  bodyBodyHair,
  bodyBulges,
  bodyCocksHard,
  bodyCocksSoft,
  bodyCocksHung,
  bodyCum,
  bodyFacialHair,
  bodyFeet,
  bodyHands,
  bodyHappyTrail,
  bodyLongHair,
  bodyMuscles,
  bodyMusk,
  bodyNipples,
  bodyPecs,
  bodyPiercings,
  bodyPubesNatural,
  bodyPubesShaved,
  bodyPubesTrimmed,
  bodyScars,
  bodySpit,
  bodyTatoos,
  clothingBaseballCaps,
  clothingBoots,
  clothingDenim,
  clothingLeather,
  clothingLingerie,
  clothingMasks,
  clothingOnsies,
  clothingRubber,
  clothingSagging,
  clothingSinglets,
  clothingSocks,
  clothingSpandexLycra,
  clothingSpeedos,
  clothingSportsUniforms,
  clothingSportsGear,
  clothingSuits,
  clothingUniforms,
  clothingUnderwear,
  clothingUnderwearBoxers,
  clothingUnderwearBoxerBriefs,
  clothingUnderwearBriefs,
  clothingUnderwearJockstraps,
  clothingUnderwearMesh,
  clothingUnderwearNylons,
  clothingUnderwearPanties,
  clothingUnderwearUsed,
  clothingUnderwearTightyWhities,
}

extension FetishLabel on Fetish {
  static const _pt = {
    Fetish.bodyArmpits: 'Axilas',
    Fetish.bodyAss: 'Bunda',
    Fetish.bodyBodyHair: 'Pelos no Corpo',
    Fetish.bodyBulges: 'Pacotes',
    Fetish.bodyCocksHard: 'Pau Duro',
    Fetish.bodyCocksSoft: 'Pau Mole',
    Fetish.bodyCocksHung: 'Pau Dotado',
    Fetish.bodyCum: 'Porra',
    Fetish.bodyFacialHair: 'Barba',
    Fetish.bodyFeet: 'Pés',
    Fetish.bodyHands: 'Mãos',
    Fetish.bodyHappyTrail: 'Trilha de Pelos',
    Fetish.bodyLongHair: 'Cabelo Longo',
    Fetish.bodyMuscles: 'Músculos',
    Fetish.bodyMusk: 'Cheiro Natural',
    Fetish.bodyNipples: 'Mamilos',
    Fetish.bodyPecs: 'Peitorais',
    Fetish.bodyPiercings: 'Piercings',
    Fetish.bodyPubesNatural: 'Bush (púbis)',
    Fetish.bodyPubesShaved: 'Raspado (púbis)',
    Fetish.bodyPubesTrimmed: 'Aparado (púbis)',
    Fetish.bodyScars: 'Cicatrizes',
    Fetish.bodySpit: 'Cuspe',
    Fetish.bodyTatoos: 'Tatuagens',
    Fetish.clothingBaseballCaps: 'Bonés de Beisebol',
    Fetish.clothingBoots: 'Botas',
    Fetish.clothingDenim: 'Denim',
    Fetish.clothingLeather: 'Couro',
    Fetish.clothingLingerie: 'Lingerie',
    Fetish.clothingMasks: 'Máscaras',
    Fetish.clothingOnsies: 'Macacões',
    Fetish.clothingRubber: 'Borracha',
    Fetish.clothingSagging: 'Calças caindo',
    Fetish.clothingSinglets: 'Regatas',
    Fetish.clothingSocks: 'Meias',
    Fetish.clothingSpandexLycra: 'Spandex/Lycra',
    Fetish.clothingSpeedos: 'Sunga',
    Fetish.clothingSportsUniforms: 'Uniformes Esportivos',
    Fetish.clothingSportsGear: 'Equipamento Esportivo',
    Fetish.clothingSuits: 'Ternos',
    Fetish.clothingUniforms: 'Uniformes',
    Fetish.clothingUnderwear: 'Roupa Íntima',
    Fetish.clothingUnderwearBoxers: 'Cuecas',
    Fetish.clothingUnderwearBoxerBriefs: 'Samba-canção',
    Fetish.clothingUnderwearBriefs: 'Slips',
    Fetish.clothingUnderwearJockstraps: 'Jockstraps',
    Fetish.clothingUnderwearMesh: 'Malha',
    Fetish.clothingUnderwearNylons: 'Meias-calças',
    Fetish.clothingUnderwearPanties: 'Calcinhas',
    Fetish.clothingUnderwearUsed: 'Roupa Íntima Usada',
    Fetish.clothingUnderwearTightyWhities: 'Cuecas Brancas',
  };

  String get label => _pt[this]!;
}