enum Kink {
  bdsm,
  bondage,
  chastity,
  cmnm,
  cumPlay,
  edging,
  enimas,
  exhibitionism,
  facials,
  fisting,
  freeballing,
  fleshlights,
  gagsTape,
  gasMasks,
  gloryholes,
  groups,
  humiliation,
  mirrorPlay,
  pigPlay,
  porn,
  sexToys,
  sexDolls,
  shaving,
  sounding,
  spanking,
  voyeurism,
  watersports,
  wedgies,
  whipping,
  agePlay,
  classrooms,
  costumePlay,
  deliveryGuy,
  doctorPatient,
  firstTime,
  furry,
  handyMan,
  publicLockerRooms,
  publicNudity,
  publicRestrooms,
  publicShowers,
  pupPlay,
  slaveMaster,
  sleepPlay,
  slumberParty,
  superhero,
}

extension KinkLabel on Kink {
  static const _pt = {
    Kink.bdsm: 'BDSM',
    Kink.bondage: 'Bondage/Corda',
    Kink.chastity: 'Castidade',
    Kink.cmnm: 'CMNM (Clothed-Male, Nude-Male)',
    Kink.cumPlay: 'Cum Play',
    Kink.edging: 'Edging',
    Kink.enimas: 'Enemas',
    Kink.exhibitionism: 'Exibicionismo',
    Kink.facials: 'Facial',
    Kink.fisting: 'Punho / Fisting',
    Kink.freeballing: 'Sem Cueca',
    Kink.fleshlights: 'Fleshlights',
    Kink.gagsTape: 'Mordaças/Fita',
    Kink.gasMasks: 'Máscaras de gás',
    Kink.gloryholes: 'Buracos de Glória',
    Kink.groups: 'Sexo em Grupo',
    Kink.humiliation: 'Humilhação',
    Kink.mirrorPlay: 'Espelhos',
    Kink.pigPlay: 'Pig (Sujo)',
    Kink.porn: 'Porno',
    Kink.sexToys: 'Brinquedos Sexuais',
    Kink.sexDolls: 'Bonecas sexuais',
    Kink.shaving: 'Depilar',
    Kink.sounding: 'Soando',
    Kink.spanking: 'Espancar / Surra',
    Kink.voyeurism: 'Voyeurismo',
    Kink.watersports: 'Esportes Aquáticos',
    Kink.wedgies: 'Cuecão',
    Kink.whipping: 'Chicotadas/Açoites',
    Kink.agePlay: 'Papai / Filho',
    Kink.classrooms: 'Sala de Aula',
    Kink.costumePlay: 'Fantasia',
    Kink.deliveryGuy: 'Rapaz das entregas',
    Kink.doctorPatient: 'Médico/Paciente',
    Kink.firstTime: 'Primeira vez',
    Kink.furry: 'Furries',
    Kink.handyMan: 'Trabalhador Braçal',
    Kink.publicLockerRooms: 'Vestiários públicos',
    Kink.publicNudity: 'Nudez pública',
    Kink.publicRestrooms: 'Banheiros Públicos',
    Kink.publicShowers: 'Banhos Públicos',
    Kink.pupPlay: 'Pup Play',
    Kink.slaveMaster: 'Escravo/Mestre',
    Kink.sleepPlay: 'Sleep Play',
    Kink.slumberParty: 'Festa do Pijama',
    Kink.superhero: 'Super-herói',
  };

  String get label => _pt[this]!;
}