name: snarf
description: "snarf"

publish_to: 'none'

version: 1.4.2+42

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  flutter_map: ^8.1.1
  geolocator: ^14.0.0
  provider: ^6.1.5
  latlong2: ^0.9.1
  signalr_netcore: ^1.4.3
  uuid: ^4.5.1
  jwt_decode: ^0.3.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  pro_image_editor: ^9.7.3
  chewie: ^1.11.3
  video_player: ^2.9.5
  permission_handler: ^12.0.0+1
  video_compress: ^3.1.4
  audioplayers: ^6.4.0
  record: ^6.0.0
  image: ^4.5.4
  jitsi_meet_flutter_sdk: ^11.1.1
  emoji_picker_flutter: ^4.3.0
  url_launcher: ^6.3.1
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  in_app_update: ^4.2.3
  flutter_launcher_icons: ^0.14.3
  in_app_purchase: ^3.2.1
  jwt_decoder: ^2.0.1
  font_awesome_flutter: ^10.8.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/snarf-icon512px.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/photo1.png
    - assets/photo2.png
    - assets/photo3.png
    - assets/photo4.png