name: snarf
description: "snarf"

publish_to: 'none'

version: 1.2.4+24

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  flutter_map: ^7.0.2
  location: ^8.0.0
  provider: ^6.1.2
  latlong2: ^0.9.1
  signalr_netcore: ^1.4.0
  uuid: ^4.5.1
  jwt_decode: ^0.3.1
  intl: ^0.20.1
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  pro_image_editor: ^8.1.0
  chewie: ^1.10.0
  video_player: ^2.9.2
  permission_handler: ^11.3.1
  video_compress: ^3.1.3
  audioplayers: ^6.1.1
  record: ^5.2.0
  image: ^4.5.2
  jitsi_meet_flutter_sdk: ^10.3.0
  emoji_picker_flutter: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/